version: '3.9'
services:
  api:
    build: ./backend
    ports: ["8080:8080"]
  web:
    build: ./frontend
    environment:
      - VITE_API_URL=http://localhost:8080
    ports: ["5173:80"]
    depends_on: [api]
